ARG RUST_IMAGE=docker.io/library/rust:1.97.1-alpine3.23@sha256:c4a364ddbf684fe038e6fa6a4f25b30c8dc85247423e0e660676ece0d17be4a2
ARG RUNTIME_IMAGE=registry.suse.com/suse/sl-micro/6.2/base-os-container:latest@sha256:3f0f52e7f4055048893c39b6bf039db9c573f5ce999cd45367de5016acf5839b
ARG FLUXHEIM_CONFIG=packaging/container/fluxheim.toml

FROM ${RUST_IMAGE} AS builder
WORKDIR /usr/src/fluxheim

RUN apk add --no-cache build-base cmake perl pkgconf \
    && mkdir -p scripts

COPY Cargo.toml Cargo.lock rust-toolchain.toml ./
COPY build.rs ./
COPY vendor ./vendor
COPY packaging/systemd ./packaging/systemd
COPY crates ./crates
COPY src ./src
COPY scripts/validate-features.sh scripts/feature-policy.sh ./scripts/

ARG FLUXHEIM_FEATURES=profile-full,acme-client,metrics,metrics-otlp,otel-tracing,otel-otlp
RUN if [ "${FLUXHEIM_FEATURES}" = "default" ]; then \
        cargo build --locked --release; \
    else \
        scripts/validate-features.sh "${FLUXHEIM_FEATURES}" && \
        cargo build --locked --release --no-default-features --features "${FLUXHEIM_FEATURES}"; \
    fi

FROM ${RUNTIME_IMAGE}
ARG FLUXHEIM_CONFIG=packaging/container/fluxheim.toml
ARG FLUXHEIM_RUNTIME_UID=65532
ARG FLUXHEIM_RUNTIME_GID=65532

LABEL org.opencontainers.image.title="Fluxheim"
LABEL org.opencontainers.image.description="Fluxheim static web server and reverse proxy on SUSE Linux Micro"
LABEL org.opencontainers.image.licenses="EUPL-1.2"
LABEL org.opencontainers.image.source="https://github.com/valkyoth/fluxheim"

RUN mkdir -p /etc/ssl/certs /etc/fluxheim /run/fluxheim /var/lib/fluxheim/acme /var/cache/fluxheim /var/log/fluxheim /srv/fluxheim \
    && chown -R ${FLUXHEIM_RUNTIME_UID}:${FLUXHEIM_RUNTIME_GID} /etc/fluxheim /run/fluxheim /var/lib/fluxheim /var/cache/fluxheim /var/log/fluxheim /srv/fluxheim

COPY --from=builder /etc/ssl/certs/ca-certificates.crt /etc/ssl/certs/ca-certificates.crt
COPY --from=builder /usr/src/fluxheim/target/release/fluxheim /usr/local/bin/fluxheim
COPY --from=builder /usr/src/fluxheim/target/release/fluxheim-acme /usr/local/bin/fluxheim-acme
COPY ${FLUXHEIM_CONFIG} /etc/fluxheim/fluxheim.toml
COPY packaging/default/index.html /srv/fluxheim/index.html

USER ${FLUXHEIM_RUNTIME_UID}:${FLUXHEIM_RUNTIME_GID}
EXPOSE 8080 8443

ENTRYPOINT ["/usr/local/bin/fluxheim"]
CMD ["--config", "/etc/fluxheim/fluxheim.toml"]
