use std::path::PathBuf;

use super::AcmeInitIssuer;

#[derive(Debug)]
pub(super) struct CacheWarmOptions<'a> {
    pub(super) config_path: Option<&'a std::path::Path>,
    pub(super) listen: Option<String>,
    pub(super) host: Option<String>,
    pub(super) headers: Vec<String>,
    pub(super) paths: Vec<String>,
    pub(super) input: Option<PathBuf>,
    pub(super) timeout_secs: u64,
    pub(super) max_targets: usize,
    pub(super) fail_fast: bool,
    pub(super) dry_run: bool,
    pub(super) repeat: usize,
    pub(super) allow_statuses: Vec<u16>,
    pub(super) cache_status_header: String,
    pub(super) expect_cache_statuses: Vec<String>,
    pub(super) expect_cache_status_sequence: Vec<String>,
}

#[derive(Debug)]
pub(super) struct CacheKeyOptions<'a> {
    pub(super) config_path: Option<&'a std::path::Path>,
    pub(super) host: Option<String>,
    pub(super) headers: Vec<String>,
    pub(super) method: String,
    pub(super) path: String,
    pub(super) query: Option<String>,
    pub(super) expect_eligible: bool,
    pub(super) expect_ineligible: bool,
    pub(super) expect_reason: Option<String>,
    pub(super) expect_cache_lock_enabled: bool,
    pub(super) expect_cache_lock_wait_timeout_secs: Option<u64>,
    pub(super) expect_cache_predictor_enabled: bool,
    pub(super) expect_origin_protection_enabled: bool,
    pub(super) expect_origin_protection_max_concurrent_fills: Option<usize>,
    pub(super) expect_peer_fill_enabled: bool,
    pub(super) expect_peer_fill_peers: Option<usize>,
    pub(super) expect_peer_fill_max_concurrent_requests: Option<usize>,
    pub(super) expect_memory_tier_enabled: bool,
    pub(super) expect_disk_tier_enabled: bool,
    pub(super) expect_storage_tiers: Option<u8>,
    pub(super) expect_scope: Option<String>,
    pub(super) expect_vhost: Option<String>,
    pub(super) expect_route: Option<String>,
    pub(super) expect_namespace: Option<String>,
    pub(super) expect_key_namespace: Option<String>,
    pub(super) expect_user_tag: Option<String>,
}

#[derive(Debug)]
pub(super) struct CacheLookupOptions<'a> {
    pub(super) config_path: Option<&'a std::path::Path>,
    pub(super) host: Option<String>,
    pub(super) headers: Vec<String>,
    pub(super) method: String,
    pub(super) path: String,
    pub(super) query: Option<String>,
    pub(super) require_object: bool,
    pub(super) expect_objects: Option<usize>,
    pub(super) expect_ineligible: bool,
    pub(super) expect_reason: Option<String>,
    pub(super) expect_freshness_states: Vec<String>,
    pub(super) expect_statuses: Vec<u16>,
    pub(super) expect_tiers: Vec<String>,
    pub(super) expect_fresh_ttl_secs: Vec<u64>,
    pub(super) expect_body_bytes: Vec<u64>,
    pub(super) expect_header_names: Vec<String>,
    pub(super) expect_headers: Vec<String>,
    pub(super) expect_cache_tags: Vec<String>,
    pub(super) expect_purge_indexed: bool,
    pub(super) expect_cache_lock_enabled: bool,
    pub(super) expect_cache_lock_wait_timeout_secs: Option<u64>,
    pub(super) expect_cache_predictor_enabled: bool,
    pub(super) expect_origin_protection_enabled: bool,
    pub(super) expect_origin_protection_max_concurrent_fills: Option<usize>,
    pub(super) expect_peer_fill_enabled: bool,
    pub(super) expect_peer_fill_peers: Option<usize>,
    pub(super) expect_peer_fill_max_concurrent_requests: Option<usize>,
    pub(super) expect_memory_tier_enabled: bool,
    pub(super) expect_disk_tier_enabled: bool,
    pub(super) expect_storage_tiers: Option<u8>,
    pub(super) expect_scope: Option<String>,
    pub(super) expect_vhost: Option<String>,
    pub(super) expect_route: Option<String>,
    pub(super) expect_namespace: Option<String>,
    pub(super) expect_key_namespace: Option<String>,
    pub(super) expect_user_tag: Option<String>,
    pub(super) expect_serve_stale_if_error: bool,
    pub(super) expect_serve_stale_while_revalidate: bool,
}

#[derive(Debug)]
pub(super) struct AcmeInitOptions {
    pub(super) issuer: AcmeInitIssuer,
    pub(super) email: Option<String>,
    pub(super) kid_file: Option<PathBuf>,
    pub(super) hmac_key_file: Option<PathBuf>,
    pub(super) terms_of_service_url: Option<String>,
    pub(super) accept_terms_of_service: bool,
    pub(super) non_interactive: bool,
    pub(super) force: bool,
    pub(super) no_systemd: bool,
    pub(super) output: PathBuf,
    pub(super) storage: PathBuf,
    pub(super) secrets_dir: PathBuf,
    pub(super) systemd_dropin_dir: PathBuf,
}
