[[vhosts]]
name = "www.meowmory.com"
hosts = ["www.meowmory.com"]

[vhosts.tls]
enabled = true

[vhosts.tls.certificate]
cert_path = "tls/meowmory.com/fullchain.pem"
key_path = "tls/meowmory.com/privkey.pem"

[vhosts.acme_challenge]
enabled = true
upstreams = ["host.containers.internal:8080"]

[vhosts.redirect]
enabled = true
to = "https://meowmory.com{uri}"
status = 308

[[vhosts]]
name = "meowmory.com"
hosts = ["meowmory.com"]

[vhosts.tls]
enabled = true

[vhosts.tls.certificate]
cert_path = "tls/meowmory.com/fullchain.pem"
key_path = "tls/meowmory.com/privkey.pem"

[vhosts.acme_challenge]
enabled = true
upstreams = ["host.containers.internal:8080"]

[vhosts.proxy]
upstreams = ["meowmory-app:3000"]
upstream_tls = false
connect_timeout_secs = 5
read_timeout_secs = 60
send_timeout_secs = 60

[[vhosts.proxy.error_pages]]
status = 502
path = "/meowmory_502.html"

[vhosts.proxy.error_pages.web]
root = "/srv/fluxheim/errors"
cache_control = "private, no-store"

[[vhosts]]
name = "www.ulyaoth.eu"
hosts = ["www.ulyaoth.eu"]

[vhosts.tls]
enabled = true

[vhosts.tls.certificate]
cert_path = "tls/ulyaoth.eu/fullchain.pem"
key_path = "tls/ulyaoth.eu/privkey.pem"

[vhosts.acme_challenge]
enabled = true
upstreams = ["host.containers.internal:8080"]

[vhosts.redirect]
enabled = true
to = "https://ulyaoth.eu{uri}"
status = 308

[[vhosts]]
name = "ulyaoth.eu"
hosts = ["ulyaoth.eu"]
max_request_body_bytes = "64MiB"

[vhosts.tls]
enabled = true

[vhosts.tls.certificate]
cert_path = "tls/ulyaoth.eu/fullchain.pem"
key_path = "tls/ulyaoth.eu/privkey.pem"

[vhosts.acme_challenge]
enabled = true
upstreams = ["host.containers.internal:8080"]

[vhosts.proxy]
upstreams = ["ulyaoth-app:80"]
upstream_tls = false
connect_timeout_secs = 90
read_timeout_secs = 90
send_timeout_secs = 90

[[vhosts.proxy.error_pages]]
status = 502
path = "/ulyaoth_502.html"

[vhosts.proxy.error_pages.web]
root = "/srv/fluxheim/errors"
cache_control = "private, no-store"

[[vhosts]]
name = "www.hashavatar.app"
hosts = ["www.hashavatar.app"]

[vhosts.tls]
enabled = true

[vhosts.tls.certificate]
cert_path = "tls/hashavatar.app/fullchain.pem"
key_path = "tls/hashavatar.app/privkey.pem"

[vhosts.acme_challenge]
enabled = true
upstreams = ["host.containers.internal:8080"]

[vhosts.redirect]
enabled = true
to = "https://hashavatar.app{uri}"
status = 308

[[vhosts]]
name = "hashavatar.app"
hosts = ["hashavatar.app"]

[vhosts.tls]
enabled = true

[vhosts.tls.certificate]
cert_path = "tls/hashavatar.app/fullchain.pem"
key_path = "tls/hashavatar.app/privkey.pem"

[vhosts.acme_challenge]
enabled = true
upstreams = ["host.containers.internal:8080"]

[vhosts.proxy]
upstreams = ["hashavatar-app:8080"]
upstream_tls = false
connect_timeout_secs = 5
read_timeout_secs = 60
send_timeout_secs = 60

[[vhosts.proxy.error_pages]]
status = 502
path = "/hashavatar_502.html"

[vhosts.proxy.error_pages.web]
root = "/srv/fluxheim/errors"
cache_control = "private, no-store"
