[package]
name = "fluxheim-tls"
version = "1.7.10"
edition = "2024"
rust-version = "1.97.0"
license = "EUPL-1.2"
publish = false
description = "Internal Fluxheim TLS provider and listener planning boundaries."

[features]
default = []
acme = ["dep:fluxheim-acme", "fluxheim-config/acme"]
tls-rustls-backend = ["dep:base64-ng", "dep:rustls", "dep:sanitization", "fluxheim-config/tls-rustls-backend"]
tls-rustls = ["tls-rustls-backend", "rustls/ring"]
tls-rustls-fips = ["tls-rustls-backend", "fluxheim-config/tls-rustls-fips", "rustls/fips"]
tls-openssl = ["dep:openssl", "dep:sanitization", "fluxheim-config/tls-openssl"]
tls-openssl-fips = [
    "tls-openssl",
    "dep:fluxheim-openssl-fips-support",
    "fluxheim-config/tls-openssl-fips",
]

[dependencies]
arc-swap = "1.9.2"
base64-ng = { version = "1.3.7", optional = true }
fluxheim-config = { path = "../fluxheim-config" }
fluxheim-acme = { path = "../fluxheim-acme", optional = true }
fluxheim-openssl-fips-support = { path = "../../vendor/fluxheim-openssl-fips-support", optional = true }
log = "0.4.33"
openssl = { version = "0.10.81", optional = true }
rustls = { version = "0.23.41", optional = true, default-features = false, features = ["std", "tls12", "logging"] }
sanitization = { version = "1.2.4", features = ["alloc"], optional = true }
thiserror = "2.0.18"

[dev-dependencies]
tempfile = "3.27.0"
