#!/usr/bin/env sh
set -eu

mode="${1:-check}"

case "$mode" in
    check | release)
        ;;
    *)
        echo "usage: scripts/capture-runtime-baseline.sh [check|release]" >&2
        exit 2
        ;;
esac

out_dir="${FLUXHEIM_RUNTIME_BASELINE_DIR:-target/release-evidence/runtime-baseline}"
mkdir -p "$out_dir/cargo-tree"

package_version="$(
    sed -n 's/^version = "\([^"]*\)"/\1/p' Cargo.toml | sed -n '1p'
)"
git_commit="$(
    git rev-parse HEAD 2>/dev/null || printf 'unknown'
)"
git_dirty="$(
    if [ -z "$(git status --porcelain --untracked-files=normal 2>/dev/null)" ]; then
        printf 'false'
    else
        printf 'true'
    fi
)"

{
    printf 'schema_version=1\n'
    printf 'mode=%s\n' "$mode"
    printf 'package_version=%s\n' "$package_version"
    printf 'git_commit=%s\n' "$git_commit"
    printf 'git_dirty=%s\n' "$git_dirty"
    printf 'captured_utc=%s\n' "$(date -u '+%Y-%m-%dT%H:%M:%SZ')"
    printf 'host_uname=%s\n' "$(uname -a | tr '\t' ' ')"
    printf 'rustc=%s\n' "$(rustc --version)"
    printf 'cargo=%s\n' "$(cargo --version)"
} >"$out_dir/metadata.env"

capture_tree() {
    profile="$1"
    tree_file="$out_dir/cargo-tree/$profile.txt"

    case "$profile" in
        default)
            cargo tree --locked >"$tree_file"
            ;;
        full)
            cargo tree --locked --no-default-features --features profile-full >"$tree_file"
            ;;
        cache-edge)
            cargo tree --locked --no-default-features --features profile-cache-edge >"$tree_file"
            ;;
        proxy-edge)
            cargo tree --locked --no-default-features --features profile-proxy-edge >"$tree_file"
            ;;
        load-balancer-edge)
            cargo tree --locked --no-default-features --features profile-load-balancer-edge >"$tree_file"
            ;;
        native-web-tls)
            cargo tree --locked --no-default-features --features web,tls-rustls >"$tree_file"
            ;;
        native-web-openssl)
            cargo tree --locked --no-default-features --features web,tls-openssl >"$tree_file"
            ;;
        php)
            cargo tree --locked --no-default-features --features profile-web-server,php-fpm >"$tree_file"
            ;;
        privacy)
            cargo tree --locked --no-default-features --features profile-privacy >"$tree_file"
            ;;
        *)
            echo "runtime baseline: unknown cargo-tree profile $profile" >&2
            exit 2
            ;;
    esac
}

profiles="default full cache-edge proxy-edge load-balancer-edge native-web-tls native-web-openssl php privacy"
for profile in $profiles; do
    echo "runtime baseline: cargo tree $profile"
    capture_tree "$profile"
done

{
    printf 'profile\tcrate\tversion\n'
    for profile in $profiles; do
        tree_file="$out_dir/cargo-tree/$profile.txt"
        grep -Eo 'pingora[-_a-z]* v[0-9][^ )]*' "$tree_file" \
            | sed 's/ v/\t/' \
            | sort -u \
            | while IFS="$(printf '\t')" read -r crate version; do
                printf '%s\t%s\t%s\n' "$profile" "$crate" "$version"
            done
    done
} >"$out_dir/pingora-dependency-surface.tsv"

if [ "$mode" = "release" ] || [ "${FLUXHEIM_RUNTIME_BASELINE_BUILD:-0}" = "1" ]; then
    runtime_baseline_features="${FLUXHEIM_RUNTIME_BASELINE_FEATURES:-profile-load-balancer}"
    echo "runtime baseline: building $runtime_baseline_features release binary"
    cargo build --release --locked --no-default-features --features "$runtime_baseline_features" --bin fluxheim

    binary="target/release/fluxheim"
    if [ ! -x "$binary" ]; then
        echo "runtime baseline: missing expected release binary $binary" >&2
        exit 1
    fi

    {
        printf 'profile\tpath\tbytes\n'
        bytes="$(wc -c <"$binary" | tr -d ' ')"
        printf '%s\t%s\t%s\n' "$runtime_baseline_features" "$binary" "$bytes"
    } >"$out_dir/binary-size.tsv"

    if [ "${FLUXHEIM_RUNTIME_BASELINE_PERFORMANCE:-1}" = "1" ]; then
        scripts/capture-runtime-performance-baseline.sh release
    else
        echo "runtime baseline: skipping performance baseline because FLUXHEIM_RUNTIME_BASELINE_PERFORMANCE=0"
    fi
else
    {
        printf 'profile\tpath\tbytes\n'
        printf 'default\tunmeasured\t0\n'
    } >"$out_dir/binary-size.tsv"
fi

cat >"$out_dir/README.txt" <<'EOF'
Fluxheim runtime baseline evidence.

This directory is generated by scripts/capture-runtime-baseline.sh. The 1.6.0
baseline is report-only: Pingora dependencies are expected to be present. Later
1.6.x cutover releases should tighten the release gates profile by profile until
official builds contain no Pingora crates.
EOF

echo "runtime baseline: wrote $out_dir"
